version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'monthly'
      time: '02:00'
    open-pull-requests-limit: 20
    groups:
      babel:
        patterns:
          - '@babel/*'
          - 'babel*'
          - 'metro-react-native-babel-preset'
      prettier:
        patterns:
          - 'eslint-config-prettier'
          - 'prettier*'
      react:
        patterns:
          - '@types/react'
          - 'react'
      react-native:
        patterns:
          - '@react-native/*'
          - 'react-native*'
          - '@react-native-community/*'
          - '@react-navigation/*'
        exclude-patterns:
          - 'react-native-builder-bob'
      react-navigation:
        patterns:
          - '@react-navigation/*'
      turbo:
        patterns:
          - 'eslint-config-turbo'
          - 'turbo'
      vitest:
        patterns:
          - 'eslint-plugin-vitest'
          - 'vitest'
          - 'vitest-react-native'
    reviewers:
      - mburumaxwell
  - package-ecosystem: 'github-actions'
    directory: /
    schedule:
      interval: 'monthly'
      time: '02:00'
    open-pull-requests-limit: 10
    reviewers:
      - mburumaxwell

  - package-ecosystem: 'gradle'
    directories:
      - '/examples/identity/android'
      - '/packages/identity/android'
    schedule:
      interval: 'monthly'
      time: '02:00'
    open-pull-requests-limit: 10
    reviewers:
      - mburumaxwell
    groups:
      react-native:
        patterns:
          - 'com.facebook.react:*'
  - package-ecosystem: 'swift'
    directories:
      - '/examples/identity/ios'
      - '/packages/identity/ios'
    schedule:
      interval: 'monthly'
      time: '02:00'
    open-pull-requests-limit: 10
    reviewers:
      - mburumaxwell
