version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
      time: '02:00'
    open-pull-requests-limit: 10
    groups:
      babel:
        patterns:
          - '@babel/*'
          - 'babel*'
          - 'metro-react-native-babel-preset'
      prettier:
        patterns:
          - 'eslint-config-prettier'
          - 'prettier*'
      react:
        patterns:
          - '@types/react'
          - 'react'
      react-native:
        patterns:
          - '@react-native/*'
          - 'react-native*'
          - '@react-native-community/*'
          - '@react-navigation/*'
        exclude-patterns:
          - 'react-native-builder-bob'
      react-navigation:
        patterns:
          - '@react-navigation/*'
      turbo:
        patterns:
          - 'eslint-config-turbo'
          - 'turbo'
      vitest:
        patterns:
          - 'eslint-plugin-vitest'
          - 'vitest'
          - 'vitest-react-native'
    reviewers:
      - mburumaxwell
      - sethonyango
  - package-ecosystem: 'github-actions'
    directory: /
    schedule:
      interval: 'weekly'
      time: '02:00'
    open-pull-requests-limit: 10
    reviewers:
      - mburumaxwell
      - sethonyango

  - package-ecosystem: 'gradle'
    directory: '/examples/identity/android'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    reviewers:
      - sethonyango
    groups:
      gradle-packages:
        patterns: ['*']
  - package-ecosystem: 'gradle'
    directory: '/packages/identity/android'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    reviewers:
      - sethonyango
    groups:
      gradle-packages:
        patterns: ['*']
  - package-ecosystem: 'swift'
    directory: '/examples/identity/ios'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    reviewers:
      - sethonyango
    groups:
      swift-packages:
        patterns: ['*']
  - package-ecosystem: 'swift'
    directory: '/packages/identity/ios'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    reviewers:
      - sethonyango
    groups:
      swift-packages:
        patterns: ['*']
