name: Android
description: Build Identity Verification framework and android app

runs:
  using: composite
  steps:
    - name: Install JDK
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "17"

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/wrapper
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('examples/android/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build example for Android
      shell: bash
      env:
        JAVA_OPTS: "-XX:MaxHeapSize=6g"
      run: |
        cd examples/identity && pnpm build:android
